package entidades;
// Generated 19-jul-2019 9:58:34 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private String nombres;
     private String apellidos;
     private Date fechanaci;
     private String direccion;
     private String telefono;
     private String email;
     private Set mascotaporclientes = new HashSet(0);
     private Set usuarios = new HashSet(0);
     private Set reservacistas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int idCliente, String nombres, String apellidos, Date fechanaci, String direccion, String telefono, String email) {
        this.idCliente = idCliente;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.fechanaci = fechanaci;
        this.direccion = direccion;
        this.telefono = telefono;
        this.email = email;
    }
    public Cliente(int idCliente, String nombres, String apellidos, Date fechanaci, String direccion, String telefono, String email, Set mascotaporclientes, Set usuarios, Set reservacistas) {
       this.idCliente = idCliente;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.fechanaci = fechanaci;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.mascotaporclientes = mascotaporclientes;
       this.usuarios = usuarios;
       this.reservacistas = reservacistas;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Date getFechanaci() {
        return this.fechanaci;
    }
    
    public void setFechanaci(Date fechanaci) {
        this.fechanaci = fechanaci;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getMascotaporclientes() {
        return this.mascotaporclientes;
    }
    
    public void setMascotaporclientes(Set mascotaporclientes) {
        this.mascotaporclientes = mascotaporclientes;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getReservacistas() {
        return this.reservacistas;
    }
    
    public void setReservacistas(Set reservacistas) {
        this.reservacistas = reservacistas;
    }




}


