package entidades;
// Generated 19-jul-2019 9:58:34 by Hibernate Tools 4.3.1



/**
 * Tipoatencion generated by hbm2java
 */
public class Tipoatencion  implements java.io.Serializable {


     private int idTipoAtencion;
     private String descripcion;

    public Tipoatencion() {
    }

    public Tipoatencion(int idTipoAtencion, String descripcion) {
       this.idTipoAtencion = idTipoAtencion;
       this.descripcion = descripcion;
    }
   
    public int getIdTipoAtencion() {
        return this.idTipoAtencion;
    }
    
    public void setIdTipoAtencion(int idTipoAtencion) {
        this.idTipoAtencion = idTipoAtencion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


